name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.12.2
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0-nullsafety
  flutter:
    sdk: flutter
  path_drawing: ^0.5.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
